name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32
        path: ''

    - uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: |
          ${{ github.workspace }}/build/bootloader/bootloader.bin
          ${{ github.workspace }}/build/partition_table/partition-table.bin
          ${{ github.workspace }}/build/ion1-nowifi.bin
